trigger:
  - main

pool:
  name: "Default"

variables:
  ArtifactName: "drop"
  DeployPath: "$HOME/deploy/grupo03-static"

stages:
  - stage: Build
    displayName: Build + Artefacto
    jobs:
      - job: BuildJob
        steps:
          - checkout: self

          - script: |
              echo "== Evidencia de agente/máquina =="
              echo "Agent.Name=$(Agent.Name)"
              echo "Agent.MachineName=$(Agent.MachineName)"
              echo "Agent.OS=$(Agent.OS)"
              uname -a || true
            displayName: "Evidencia: agente"

          - script: |
              echo "== Build (simple) =="
              mkdir -p artifact

              # "Software" a desplegar (estático)
              cp index.html artifact/

              # Evidencia
              {
                echo "REPORTE PIPELINE"
                echo "---------------"
                echo "BuildId: $(Build.BuildId)"
                echo "Commit : $(Build.SourceVersion)"
                echo "Branch : $(Build.SourceBranch)"
                echo "Fecha  : $(Build.QueuedTime)"
              } > artifact/build_info.txt

              echo "Contenido artifact:"
              ls -la artifact
            displayName: "Preparar artefacto"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.SourcesDirectory)/artifact"
              artifact: "$(ArtifactName)"
            displayName: "Publicar artefacto"

  - stage: Deploy
    displayName: Deploy (local VM)
    dependsOn: Build
    jobs:
      - deployment: DeployJob
        displayName: Deploy usando Environment
        environment: "env-grupo03-vm"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: $(ArtifactName)

                - script: |
                    set -e
                    echo "== Deploy REAL local =="
                    SRC="$(Pipeline.Workspace)/$(ArtifactName)"
                    DEST="$(DeployPath)"

                    echo "Origen : $SRC"
                    echo "Destino: $DEST"
                    mkdir -p "$DEST"

                    echo "Copiando..."
                    cp -r "$SRC/"* "$DEST/"

                    echo "Verificando:"
                    ls -la "$DEST"
                    echo ""
                    echo "build_info.txt:"
                    cat "$DEST/build_info.txt"
                  displayName: "Deploy: copiar + verificar"
