trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
stages:
# -------------------------
# 1) BUILD
# -------------------------
- stage: Build
  displayName: Build app
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
 
    - script: |
        echo "Compilando..."
        # aquí va tu build real
      displayName: Build
 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'drop'
      displayName: Publicar artefacto
 
# -------------------------
# 2) DEPLOY (a la VM con Environment)
# -------------------------
- stage: Deploy
  displayName: Deploy to VM
  dependsOn: Build
  jobs:
  - deployment: DeployJob
    displayName: Deploy usando Environment
    environment: 'env-grupo03-vm'   # <-- nombre del Environment en Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
 
          - script: |
              echo "Desplegando en la VM..."
              ls -la
              # Ejemplo: copiar a carpeta del servidor
              # sudo cp -r $(Pipeline.Workspace)/drop/* /var/www/html/
            displayName: Deploy
